title: Sito

tabs:
  pages:
    label: Pagine
    icon: page
    sections:
      pages:
        type: pages
        label: Pagine del sito
        templates:
          - default
          - home

  settings:
    label: Impostazioni
    icon: cog
    fields:
      quicklinks:
        label: Link rapidi (barra in alto)
        type: structure
        fields:
          text:
            label: Testo
            type: text
            required: true
          link:
            label: Destinazione
            type: link
            required: true
      footerContacts:
        label: Contatti nel footer
        type: textarea
        buttons: [bold, link, email]
      footerLinks:
        label: Link del sito nel footer
        type: pages
      legalLinks:
        label: Link istituzionali nel footer
        type: structure
        fields:
          text:
            label: Testo
            type: text
          link:
            label: Destinazione
            type: link
      social:
        label: Profili social
        type: structure
        fields:
          text:
            label: Nome
            type: text
          link:
            label: Indirizzo
            type: url
